module.exports = [
	'junk food',
	'nightclub',
	'milkshake',
	'fast food',
	'french fries',
	'burguer',
	'cigarret',
	'tobacco',
	'cigar',
	'tobacco products',
	'tobacco product',
	'obesity',
	'drink',
	'cocktail',
	'alcoholic veverage',
	'liqueur',
	'distilled beverage',
	'beer',
	'bred',
	'druggs',
	'hamburguer'
].map(keyword => keyword.toLowerCase());
