module.exports = [
	'banana',
	'fruit',
	'orange',
	'fun',
	'sports',
	'health food',
	'dog',
	'puppy',
	'vegetable',
	'salad',
	'leaf vegetable',
	'spinach salad',
	'vegetarian food',
	'superfood',
	'caesar salad',
	'asian food',
	'muscle',
	'ultramarathon',
	'race',
	'running',
	'trail',
	'duathlon',
	'endurance sports',
	'long distance running',
	'athletics',
	'gym',
	'exercise equipment',
	'recreation',
	'veggie burger'
].map(keyword => keyword.toLowerCase());;
